name: Java CI with gradle

on:
  push:
    branches: main

jobs:
  build-and-push-image:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USER }}/dado-api-mem:latest .
    - name: Publish Docker image
      run: docker push ${{ secrets.DOCKER_USER }}/dado-api-mem:latest